pyporscheconnectapi/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
pyporscheconnectapi/cli.py,sha256=xVODgnQveyYwepezaY7wDhfTeYv3qIonMTJx5raMZI8,10930
pyporscheconnectapi/client.py,sha256=20OpxoihjWPrlRBy01DDgaLDBphrjqlPx0wrkCo68yU,19856
pyporscheconnectapi/connection.py,sha256=9SwvbWrw4zMFqx9-PgoZeJHhRP-GxOCA_jFAO5VD67k,12251
pyporscheconnectapi/exceptions.py,sha256=Ez_D_TsafBd59LRIKRvGFv_6W9Ia425QCaClwXEke2w,1539
pyporscheconnectapi-0.1.1.dist-info/LICENSE,sha256=3wo4ylCH88NDNuSoNFaeaNCdzpQDloqsIUDQMg5FWec,1071
pyporscheconnectapi-0.1.1.dist-info/METADATA,sha256=LJokancyE_pJpEH7ZnlkyRSEbRFLa0p3bherYYCWlRg,4988
pyporscheconnectapi-0.1.1.dist-info/WHEEL,sha256=pkctZYzUS4AYVn6dJ-7367OJZivF2e8RA9b_ZBjif18,92
pyporscheconnectapi-0.1.1.dist-info/entry_points.txt,sha256=TyK7SoobnS8fJ_Pwmz6mJOkug4eYb9Mq8tU6WhgBaBg,59
pyporscheconnectapi-0.1.1.dist-info/top_level.txt,sha256=YXSR3DO6I6QQ0lEQOvTts5BFIGsfOw_WtdFlD8BN4Yw,20
pyporscheconnectapi-0.1.1.dist-info/RECORD,,
